name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # ✅ required for creating/uploading releases

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }} # ✅ ensures target is installed

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/dinfo* dist/ || true
          cd dist
          zip dinfo-${{ matrix.target }}.zip dinfo* || true

      - name: Package binary (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir -p dist
          copy "target\${{ matrix.target }}\release\dinfo*" dist\ 2>nul || echo "Copy completed"
          cd dist
          powershell Compress-Archive -Path dinfo* -DestinationPath dinfo-${{ matrix.target }}.zip

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
